version: '3.8'

services:
  c2server:
    build: .
    ports:
      - "443:443"
    environment:
      - C2_SERVER_HOST=0.0.0.0
      - C2_SERVER_PORT=443
      - C2_SERVER_URL=https://127.0.0.1:443
      - C2_SHARED_SECRET=aswqiwn123wedb
      - C2_LOG_LEVEL=INFO
      - C2_ADMIN_USER=admin
      - C2_ADMIN_PASS=secure_password_here
    volumes:
      - ./certs:/app/certs
    restart: unless-stopped